<div class="col-md-9 no-padding">
    <div class="tp-banner-container">
        <div class="tp-banner with-bg-slide">
            <ul>
                <li data-transition="random" data-slotamount="7" data-masterspeed="300"  data-saveperformance="off" >
                    <img src="/images/trans-bg.png"  alt="slider"  data-bgposition="center bottom" data-bgfit="cover" data-bgrepeat="no-repeat"> 
                    <div class="tp-caption sfl tp-resizeme" 
                         data-x="left" data-hoffset="100" 
                         data-y="center" data-voffset="-80" 
                         data-speed="800" 
                         data-start="800" 
                         data-easing="Power3.easeInOut" 
                         data-splitin="chars" 
                         data-splitout="none" 
                         data-elementdelay="0.03" 
                         data-endelementdelay="0.4" 
                         data-endspeed="300"
                         style="z-index: 5; font-size:24px; font-weight:500; color:#888888;  max-width: auto; max-height: auto; white-space: nowrap;">High Quality VR Glasses </div>
                    <div class="tp-caption sfr tp-resizeme" 
                         data-x="left" data-hoffset="100" 
                         data-y="center" data-voffset="-40" 
                         data-speed="800" 
                         data-start="1000" 
                         data-easing="Power3.easeInOut" 
                         data-splitin="chars" 
                         data-splitout="none" 
                         data-elementdelay="0.03" 
                         data-endelementdelay="0.1" 
                         data-endspeed="300" 
                         style="z-index: 6; font-size:36px; color:#7a9b08; font-weight:800; white-space: nowrap;">Z68 Web Camera </div>
                    <div class="tp-caption sfr tp-resizeme" 
                         data-x="left" data-hoffset="100" 
                         data-y="center" data-voffset="10" 
                         data-speed="800" 
                         data-start="1300" 
                         data-easing="Power3.easeInOut" 
                         data-splitin="chars" 
                         data-splitout="none" 
                         data-elementdelay="0.03" 
                         data-endelementdelay="0.4" 
                         data-endspeed="300"
                         style="z-index: 5; font-size:36px; font-weight:800; color:#000;  max-width: auto; max-height: auto; white-space: nowrap;">$85.00 </div>
                    <div class="tp-caption sfr tp-resizeme" 
                         data-x="right" data-hoffset="-100" 
                         data-y="center" data-voffset="0" 
                         data-speed="800" 
                         data-start="1300"
                         data-easing="Power3.easeInOut" 
                         data-elementdelay="0.1" 
                         data-endelementdelay="0.1" 
                         data-endspeed="300" 
                         data-scrolloffset="0"
                         style="z-index: 9;"><img src="images/slide-item-1.png" alt="" > </div>
                    <div class="tp-caption lfb tp-resizeme" 
                         data-x="left" data-hoffset="100" 
                         data-y="center" data-voffset="100"
                         data-speed="800" 
                         data-start="1300"
                         data-easing="Power3.easeInOut" 
                         data-elementdelay="0.1" 
                         data-endelementdelay="0.1" 
                         data-endspeed="300" 
                         data-scrolloffset="0"
                         style="z-index: 8;"><a href="/#." class="btn-round big">Shop Now</a> </div>
                </li>
                <li data-transition="random" data-slotamount="7" data-masterspeed="300"  data-saveperformance="off" >
                    <img src="/images/trans-bg.png"  alt="slider"  data-bgposition="center bottom" data-bgfit="cover" data-bgrepeat="no-repeat"> 
                    <div class="tp-caption sfl tp-resizeme" 
                         data-x="left" data-hoffset="100" 
                         data-y="center" data-voffset="-80" 
                         data-speed="800" 
                         data-start="800" 
                         data-easing="Power3.easeInOut" 
                         data-splitin="chars" 
                         data-splitout="none" 
                         data-elementdelay="0.03" 
                         data-endelementdelay="0.4" 
                         data-endspeed="300"
                         style="z-index: 5; font-size:24px; font-weight:500; color:#888888;  max-width: auto; max-height: auto; white-space: nowrap;">Connecting Music, Emotions & Spaces </div>
                    <div class="tp-caption sfr tp-resizeme" 
                         data-x="left" data-hoffset="100" 
                         data-y="center" data-voffset="-40" 
                         data-speed="800" 
                         data-start="1000" 
                         data-easing="Power3.easeInOut" 
                         data-splitin="chars" 
                         data-splitout="none" 
                         data-elementdelay="0.03" 
                         data-endelementdelay="0.1" 
                         data-endspeed="300" 
                         style="z-index: 6; font-size:36px; color:#7a9b08; font-weight:800; white-space: nowrap;">Speaker M5 </div>
                    <div class="tp-caption sfr tp-resizeme" 
                         data-x="left" data-hoffset="100" 
                         data-y="center" data-voffset="10" 
                         data-speed="800" 
                         data-start="1300" 
                         data-easing="Power3.easeInOut" 
                         data-splitin="chars" 
                         data-splitout="none" 
                         data-elementdelay="0.03" 
                         data-endelementdelay="0.4" 
                         data-endspeed="300"
                         style="z-index: 5; font-size:36px; font-weight:800; color:#000;  max-width: auto; max-height: auto; white-space: nowrap;">$250.00 </div>
                    <div class="tp-caption sfr tp-resizeme" 
                         data-x="right" data-hoffset="-100" 
                         data-y="center" data-voffset="0" 
                         data-speed="800" 
                         data-start="1300"
                         data-easing="Power3.easeInOut" 
                         data-elementdelay="0.1" 
                         data-endelementdelay="0.1" 
                         data-endspeed="300" 
                         data-scrolloffset="0"
                         style="z-index: 9;"><img src="/images/slide-item-2.png" alt="" > </div>
                    <div class="tp-caption lfb tp-resizeme" 
                         data-x="left" data-hoffset="100" 
                         data-y="center" data-voffset="100"
                         data-speed="800" 
                         data-start="1300"
                         data-easing="Power3.easeInOut" 
                         data-elementdelay="0.1" 
                         data-endelementdelay="0.1" 
                         data-endspeed="300" 
                         data-scrolloffset="0"
                         style="z-index: 8;"><a href="/#." class="btn-round big">Shop Now</a> </div>
                </li>
                <li data-transition="random" data-slotamount="7" data-masterspeed="300"  data-saveperformance="off" >
                    <img src="/images/trans-bg.png"  alt="slider"  data-bgposition="center bottom" data-bgfit="cover" data-bgrepeat="no-repeat"> 
                    <div class="tp-caption sfl tp-resizeme" 
                         data-x="left" data-hoffset="100" 
                         data-y="center" data-voffset="-80" 
                         data-speed="800" 
                         data-start="800" 
                         data-easing="Power3.easeInOut" 
                         data-splitin="chars" 
                         data-splitout="none" 
                         data-elementdelay="0.03" 
                         data-endelementdelay="0.4" 
                         data-endspeed="300"
                         style="z-index: 5; font-size:24px; font-weight:500; color:#888888;  max-width: auto; max-height: auto; white-space: nowrap;">Get Free Gear 360 when buy </div>
                    <div class="tp-caption sfr tp-resizeme" 
                         data-x="left" data-hoffset="100" 
                         data-y="center" data-voffset="-40" 
                         data-speed="800" 
                         data-start="1000" 
                         data-easing="Power3.easeInOut" 
                         data-splitin="chars" 
                         data-splitout="none" 
                         data-elementdelay="0.03" 
                         data-endelementdelay="0.1" 
                         data-endspeed="300" 
                         style="z-index: 6; font-size:36px; color:#7a9b08; font-weight:800; white-space: nowrap;">Power SmartPhone s7 </div>
                    <div class="tp-caption sfr tp-resizeme" 
                         data-x="left" data-hoffset="100" 
                         data-y="center" data-voffset="10" 
                         data-speed="800" 
                         data-start="1300" 
                         data-easing="Power3.easeInOut" 
                         data-splitin="chars" 
                         data-splitout="none" 
                         data-elementdelay="0.03" 
                         data-endelementdelay="0.4" 
                         data-endspeed="300"
                         style="z-index: 5; font-size:36px; font-weight:800; color:#000;  max-width: auto; max-height: auto; white-space: nowrap;">$349.99 </div>
                    <div class="tp-caption sfr tp-resizeme"
                         data-x="right" data-hoffset="-100" 
                         data-y="center" data-voffset="0" 
                         data-speed="800" 
                         data-start="1300"
                         data-easing="Power3.easeInOut" 
                         data-elementdelay="0.1" 
                         data-endelementdelay="0.1" 
                         data-endspeed="300" 
                         data-scrolloffset="0"
                         style="z-index: 9;"><img src="images/slide-item-3.png" alt="" > </div>
                    <div class="tp-caption lfb tp-resizeme" 
                         data-x="left" data-hoffset="100" 
                         data-y="center" data-voffset="100"
                         data-speed="800" 
                         data-start="1300"
                         data-easing="Power3.easeInOut" 
                         data-elementdelay="0.1" 
                         data-endelementdelay="0.1" 
                         data-endspeed="300" 
                         data-scrolloffset="0"
                         style="z-index: 8;"><a href="/#." class="btn-round big">Shop Now</a> </div>
                </li>
            </ul>
        </div>
    </div>
</div>